---
title: "Plotting Functions for the bayestestR Package"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{bayestestR}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE, echo=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width = 7, 
  fig.height = 5,
  warning = FALSE,
  message = FALSE,
  eval = packageVersion("bayestestR") >= "0.2.5"
)
```

```{r setup}
library(bayestestR)
library(rstanarm)
library(see)
library(ggplot2)

theme_set(theme_modern())
```

## Density Estimation

```{r eval=FALSE}
set.seed(123)
model <- rstanarm::stan_glm(Sepal.Length ~ Petal.Width * Species, data = iris)
result <- estimate_density(model)

plot(result)
```
```{r echo=FALSE}
library(bayestestR)
library(rstanarm)

junk <- capture.output(model <- rstanarm::stan_glm(Sepal.Length ~ Petal.Width * Species, data = iris))
result <- estimate_density(model)

plot(result)
```

```{r}
plot(result, stack = FALSE)
```


## Probability of Direction (pd)

```{r}
result <- p_direction(model)
plot(result)
```


## Point Estimates

```{r fig.height=10}
result <- point_estimate(model)
plot(result)
```
```{r}
result <- point_estimate(model, centrality = c("map", "mean"))
plot(result, panel = FALSE)[[5]]
```


## Highest Density Interval (HDI)

```{r}
result <- hdi(model, ci = c(0.5, 0.75, 0.89, 0.95))
plot(result) + scale_fill_flat()
```


## Region of Practical Equivalence (ROPE)

```{r echo=FALSE}
result <- rope(model, ci = c(0.9, 0.95))

plot(result, data = model, rope_color = "red") +
  scale_fill_brewer(palette = "Greens", direction = -1)
```

## Test for Practical Equivalence

```{r eval=FALSE}
model <- rstanarm::stan_glm(
  mpg ~ wt + gear + cyl + disp, data = mtcars
)
result <- equivalence_test(model)

plot(result) +
  theme_blackboard() +
  scale_fill_material()
```
```{r echo=FALSE}
junk <- capture.output(model <- rstanarm::stan_glm(mpg ~ wt + gear + cyl + disp, data = mtcars))

result <- equivalence_test(model)

plot(result) +
  theme_blackboard() +
  scale_fill_material()
```


```{r message=FALSE}
result <- equivalence_test(model, ci = c(.89, .95))

plot(result) +
  theme_abyss() +
  scale_fill_flat()
```


## Bayes Factors (BFs)

### Bayes Factors for Parameters

```{r}
result <- bayesfactor_parameters(model)

plot(result) +
  scale_color_material() +
  scale_fill_material()
```

### Bayes Factors for Model Comparison

```{r}
lm0 <- lm(qsec ~ 1, data = mtcars)
lm1 <- lm(qsec ~ drat, data = mtcars)
lm2 <- lm(qsec ~ wt, data = mtcars)
lm3 <- lm(qsec ~ drat + wt, data = mtcars)

result <- bayesfactor_models(lm1, lm2, lm3, denominator = lm0)

plot(result, n_pies = "one", value = "probability") +
  scale_fill_pizza(reverse = TRUE) 

plot(result, n_pies = "many", value = "BF") +
  scale_fill_flat(palette = "rainbow", reverse = TRUE)
```
