---
title: "Plotting Functions for the 'modelbased' Package"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Plotting Functions for the 'modelbased' Package}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include=FALSE, warning=FALSE, message=FALSE, echo=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width = 7,
  fig.height = 5,
  warning = FALSE,
  message = FALSE
)

if (!requireNamespace("rstanarm", quietly = TRUE) ||
  !requireNamespace("ggplot2", quietly = TRUE) ||
  !requireNamespace("modelbased", quietly = TRUE)) {
  knitr::opts_chunk$set(eval = FALSE)
}
```

This vignette can be referred to by citing the package:

```{r}
citation("see")
```

# Introduction

*modelbased* is a package in *easystats* ecosystem to help with model-based estimations, to easily compute of marginal means, contrast analysis and model predictions.

For more, see: <https://easystats.github.io/modelbased/>

# Setup and Model Fitting

```{r setup}
library(modelbased)
library(rstanarm)
library(ggplot2)
library(see)

theme_set(theme_modern())

model <- stan_glm(Sepal.Width ~ Species, data = iris, refresh = 0)
```

# Pairwise Contrasts

```{r}
contrasts <- estimate_contrasts(model)
means <- estimate_means(model)

plot(contrasts, means)
```
