# Run tests in random order
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Trigger once a week at 00:00 on Sunday
    - cron: "0 0 * * SUN"

name: check-random-test-order

jobs:
  check-random-test-order:
    uses: easystats/workflows/.github/workflows/check-random-test-order.yaml@main
