# Workflow derived from https://github.com/posit-dev/setup-air/tree/main/examples

name: format-suggest

on:
  pull_request_target:

jobs:
  format-suggest:
    name: format-suggest
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install
        uses: posit-dev/setup-air@v1

      - name: Format
        run: air format .

      - name: Commit styling changes
        if: github.event_name == 'pull_request'
        uses: stefanzweifel/git-auto-commit-action@v6
