on:
  push:
    branches: [main]
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Trigger once a week at 00:00 on Sunday
    - cron: "0 0 * * SUN"

name: check-styling

jobs:
  check-styling:
    uses: easystats/workflows/.github/workflows/check-styling.yaml@main
