# Running tests with options(warn = 2) to fail on test warnings
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Trigger once a week at 00:00 on Sunday
    - cron: "0 0 * * SUN"

name: check-test-warnings

jobs:
  check-test-warnings:
    uses: easystats/workflows/.github/workflows/check-test-warnings.yaml@main
