on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Trigger once a week at 00:00 on Sunday
    - cron: "0 0 * * SUN"

name: check-link-rot

jobs:
  check-link-rot:
    uses: easystats/workflows/.github/workflows/check-link-rot.yaml@main
